### ISSUE TITLE
FastMRI data set split

### ISSUE THREAD

**Issue by lilygeorgescu** [chunmeifeng/MINet#3]
Hi,

First of all, I would like to congratulate you and your team for your work.

I am also doing research on medical image super-resolution and I would like to test my new method on fastMRI data set. I have seen that the dataset is available online, but I would like to use the same split as you did. 

Could you please give me the names of the images that you trained and tested on? I would help me very much.

Best regards,
Iuliana Georgescu

**Comment by chunmeifeng** [comment]
Hi, please open this link to find the file.
https://github.com/chunmeifeng/MINet

lilygeorgescu ***@***.***> 于2022年1月17日周一 10:16写道：

**Comment by lilygeorgescu** [comment]
Thank you, I appreciate very much your quick response! 

I have seen that in the training file there are 227 rows (the same number specified in your paper), but in the validation file there are 45 rows, but only 24 images are specified in the paper. 
Should I test my model on the entire validation split? Did you use a separate set to evaluate your model like validation vs test set?

Thank you,
Iuliana Georgescu

**Comment by chunmeifeng** [comment]
Yes it's 45 rows

lilygeorgescu ***@***.***> 于2022年1月17日周一 14:05写道：
